# Generated by Django 4.1.13 on 2023-11-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='senha',
            field=models.CharField(max_length=15, verbose_name='senha'),
        ),
    ]
